### PR TITLE
Genomic interval arithmetic

### PR DESCRIPTION
**Pull request by golobor**
TODO:

AG in progress
- [x] merge updates for complement & subtract
- [ ] an ipynb with performance evaluation and comparisons
- [ ] create a module-wide configuration dictionary

GF  in progress
- [x] drop option for cluster(df) to return_cluster_df
- [x] move formats, resources, schemas --> ./io/
- [x] add technical notes section to docs, document the internal-facing format for region 
- [x] new arg overlap(on=())
- [x] new function setdiff(df1,df2)
- [x] new function split(df1,points)
- [x] delete binsize from make_chromarms, update to use ops.split(df, points)
- [x] tests for new overlap arguments (how, on=)
- [x] fix frac_gene_coverage()
- [ ] tests for: split, make_chromarms. sync split with Anton's subtract. 

Code:
- [ ] re-visit naming for: ops, genomeops, tools, _region, etc.
- [ ] new function regions_to_bins to assign binspans to a set of bp spans

Tests

Docs:
- [x] intro
- [x] design choices/philosophy
- [ ] standards and definitions
- [ ] API docs for the rest of the library
- [ ] how do I...

Demo Notebook:
https://github.com/mirnylab/bioframe/blob/genomic_interval_arithmetic/docs/notebooks/intervals_tutorials.ipynb
- [ ] update to sync w/ return changes & overlap types

Post-release
- [ ] decide how to handle pd.NA in crucial columns (chrom, start, end, on=[]). 
- [ ] accept chromsizes as dataFrame or dictionary: what should columns be called? should start=0 be required or not?
- [ ] new mode overlap(cols=(None, 'start','end'))
- [ ] split out tutorial for EncodeClient into separate ipynb

Done:
- [x] new arg overlap(how="outer")
- [x] tests for new overlap args
- [x] change outputs for frac_mapped, frac_gc to  return df, with default to append a column to input
- [x] change how returned columns are picked in cluster, coverage and nearest (split out=[...] into multiple _return_*_ boolean arguments)
- [x] tests for binnify, digest, frac_mapped, frac_gc, frac_gene_coverage
- [x] new arg cluster(on=[]), merge(on=[]), tests for this new arg
- [x] new function select(df, reg) to replace bedbisect, rename bedbisect
- [x] move genome-related functions (binnify, make_chromarms, digest, frac_mapped, frac_gc, frac_gene_coverage) to genomeops.py
- [x] delete bychrom, chromsorted
- [x] new function subtract(df1, df2)
- [x] require pandas>=1.0.3
- [x] tests for subtract, select,

### CODE REVIEW

**Comment by gfudenberg** [comment]
- [x] fix expand() when no limit is provided (see my pr)
- [ ] make decision on modifying df in place or not (e.g. expand modifies in place)
- [ ] fix n-overlaps output for coverage()
coverage-n_overlaps-issue

**Comment by golobor** [comment]
Yeah, I think ValueError is reasonable. In the future, if someone needs it,
min_dist<0 could mean some overlap? Though, it'd be cleaner to implement a
separate argument...

**Comment by golobor** [comment]
https://github.com/mirnylab/bioframe/blob/genomic_interval_arithmetic/docs/notebooks/intervals_tutorials.ipynb

**Comment by gfudenberg** [comment]
should arrops._test_overlap be renamed to _query_overlap or _check_overlap, as it is not a "test" per se ?

**Comment by golobor** [comment]
Yes!I like check overlap slightly better

**Comment by golobor** [comment]
re: cluster vs merge - merge creates a new table, while cluster augments the existing one

**Comment by gfudenberg** [comment]
These are current functions in ops with docstrings (https://bioframe.readthedocs.io/en/latest/ops.html): 
image. There is also: frac_mapped, frac_gc, frac_gene_coverage, which do not have docstrings.

If I understood one proposal was replacing: bedbisect, bedslice and bedslice_series with select(df,region). What about bg2slice ?

Also, what do you think about moving: binnify, bychrom chromsorted, make_chromarms, digest, frac_mapped, frac_gc, frac_gene_coverage into tools (or util) & deleting old (deprecated) functions living there?

**Comment by nvictus** [comment]
`bychrom` can be deleted.. it's been defunct for a long time

**Comment by golobor** [comment]
btw, what was the idea behind it?.. What was it trying to do that split-apply-combine can't?

**Comment by gfudenberg** [comment]
[ ] remove read_ucsc_rnafile, make 'ucsc.rna' a schema

**Comment by gfudenberg** [comment]
- [ ] remove read_ucsc_rnafile, make 'ucsc.rna' a schema

**Comment by golobor** [comment]
@gfudenberg , I was reading your code for subtract; I'm not sure - what's the purpose of splitting by groups? Do not complement and overlap suffice?

Unless I'm missing something, could subtract be refactored into something like:

`
def subtract(df1, df2, cols1=None, cols2=None):
    ck1, sk1, ek1 = _get_default_colnames() if cols1 is None else cols1
    ck2, sk2, ek2 = _get_default_colnames() if cols2 is None else cols2
    
    df_subtracted = bioframe.overlap(
        df1, 
        bioframe.complement(df2), 
        how="inner", 
        suffixes=['',''],
        return_input=1,
        return_overlap=True
        ).assign(start=lambda df: df['overlap_start'],
                 end=lambda df: df['overlap_end'],
        ).drop(columns=['overlap_start', 'overlap_end'])

    return df_subtracted
`

**Comment by gfudenberg** [comment]
complement currently returns complements only for those chromosomes in df2,
not those in df1 as well

**Comment by golobor** [comment]
ah, ok, then maybe complement should return whole chromosomes (from chromsizes) if that chromosome does not have any interval?

**Comment by gfudenberg** [comment]
... well then it would need to know chromosizes

**Comment by golobor** [comment]
Yeah, but then we could provide the chromosomes present in chrom1, with
sizes from 0 to np.int.maxvalue.

Anton.
(typed on a phone, sorry for brevity and typos)

**Comment by gfudenberg** [comment]
Ah! Sure that sounds cleaner. I can update. Maybe with a drop_chroms=False
key as well? In case s/o provided their own chromsizes that did not include
all of the chromosomes in df1? Or better to raise a valueError if the
provided chromsizes don't encompass the those in df1?

**Comment by golobor** [comment]
hm! In my understanding, the result of the subtract() function should
depend neither on chromsizes nor on the selection of chromosomes.
Chromsizes seem to arise in this discussion only because of the specific
implementation, overlap(df1, complement(df2)); and, in turn, complement
needs chromsizes only because some chromosomes may be missing in df2. All
of this makes me think that the subtract does not have to take any
chromosome-related information as an argument.

**Comment by nvictus** [comment]
Sweet! Let's merge this in develop and continue further developments in a new PR.

**Pull request merged**
